using BlogSeoAi.Data;
using BlogSeoAi.Models;
using Markdig;
using Microsoft.EntityFrameworkCore;

namespace BlogSeoAi.Services;

public interface IDailyPostGenerator
{
    Task<Post> GenerateAndPublishForTodayAsync(CancellationToken ct = default);
}

public class DailyPostGenerator : IDailyPostGenerator
{
    private readonly AppDbContext _db;
    private readonly IAiClient _ai;
    private readonly ISlugService _slug;
    private readonly IConfiguration _cfg;

    public DailyPostGenerator(AppDbContext db, IAiClient ai, ISlugService slug, IConfiguration cfg)
    {
        _db = db; _ai = ai; _slug = slug; _cfg = cfg;
    }

    public async Task<Post> GenerateAndPublishForTodayAsync(CancellationToken ct = default)
    {
        var topicsPath = _cfg["ContentSources:TopicsPath"]!;
        var promptPath = _cfg["ContentSources:PromptPath"]!;
        var imagesPath = _cfg["ContentSources:ImagesPath"]!;

        var topics = await File.ReadAllLinesAsync(topicsPath, ct);
        var dayOfYear = DateTime.Now.DayOfYear; // 1..365/366
        var title = (dayOfYear - 1) < topics.Length ? topics[dayOfYear - 1].Trim() : "Default Topic";

        var promptExtra = await File.ReadAllTextAsync(promptPath, ct);

        var prompt =
            $"Lütfen özellikle {title} konusu için Mağaza sahibi influencer ağzından metin oluştur! " +
            $"{title}{promptExtra}{title}";

        // Aynı gün tekrar üretmeyi engelle (idempotent)
        var sourceKey = $"day-{DateTime.UtcNow.Year}-{dayOfYear}";
        var exists = await _db.Posts.AnyAsync(p => p.AutoSourceKey == sourceKey, ct);
        if (exists)
            return await _db.Posts.OrderByDescending(p => p.Id).FirstAsync(p => p.AutoSourceKey == sourceKey, ct);

        var aiText = await _ai.GenerateAsync(prompt, ct);

        // İstersen AI çıktısı Markdown -> HTML
        var html = Markdown.ToHtml(aiText ?? "");

        // image seç
        var images = (await File.ReadAllLinesAsync(imagesPath, ct))
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .ToArray();

        var img = images.Length > 0 ? images[Random.Shared.Next(images.Length)].Trim() : null;

        var slug = await _slug.GenerateUniqueSlugAsync(title);

        var nowUtc = DateTime.UtcNow;
        var post = new Post
        {
            Title = title,
            Slug = slug,
            ContentHtml = $"<p><small>{DateTime.Now:dd MMMM yyyy HH:mm:ss}</small></p>\n{html}",
            FeaturedImageUrl = img,
            Status = PostStatus.Published,
            PublishedAtUtc = nowUtc,
            IsAutoGenerated = true,
            AutoSourceKey = sourceKey,
            SeoTitle = title,
            SeoDescription = MakeDescription(aiText, 160)
        };

        _db.Posts.Add(post);
        await _db.SaveChangesAsync(ct);
        return post;
    }

    private static string? MakeDescription(string? text, int max)
    {
        if (string.IsNullOrWhiteSpace(text)) return null;
        var t = text.Trim().Replace("\n", " ").Replace("\r", " ");
        if (t.Length <= max) return t;
        return t.Substring(0, max).Trim() + "…";
    }
}