using System.ComponentModel.DataAnnotations;

namespace BlogSeoAi.Models;

public enum PostStatus { Draft = 0, Published = 1 }

public class Post
{
    public int Id { get; set; }

    [Required, MaxLength(180)]
    public string Title { get; set; } = "";

    [Required, MaxLength(220)]
    public string Slug { get; set; } = "";

    // İçerik HTML olarak saklanır (AI + editörden gelir)
    [Required]
    public string ContentHtml { get; set; } = "";

    [MaxLength(300)]
    public string? Excerpt { get; set; }

    // SEO alanları
    [MaxLength(180)]
    public string? SeoTitle { get; set; }

    [MaxLength(300)]
    public string? SeoDescription { get; set; }

    [MaxLength(500)]
    public string? FeaturedImageUrl { get; set; }

    public PostStatus Status { get; set; } = PostStatus.Draft;

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public DateTime? PublishedAtUtc { get; set; }

    // Otomatik üretim mi?
    public bool IsAutoGenerated { get; set; }
    [MaxLength(100)]
    public string? AutoSourceKey { get; set; } // örn: "day-123"
}